### ISSUE TITLE
trove4j version conflict

### ISSUE THREAD

**Issue by pkluegl** [JULIELab/jcore-base#14]
jcore-opennlp-token-ae depends on trove4j 3.0.3
jcore-jtbd-ae depends on trove4j 2.0.2 through jcore-mallet 2.0.9

... causes java.lang.ClassNotFoundException: gnu.trove.TObjectIntHashMap when both tokenizers are used in one project.

**Comment by khituras** [comment]
I'm actually not sure that jcore-opennlp-token-ae really needs trove. I think an older version depended on it, perhaps it's an artefact from those times. Could you please try and exclude trove4j 3.0.3 from your build path (or just delete the JAR if you use a library directory) and report back if it works? In my (very) small test, the opennlp tokenizer component still worked after removing trove.

**Comment by pkluegl** [comment]
Yes, this could work, the exception is gone. I get no results yet because of some other problems (investigating...)
Is it possible to upgrade the depdence to 3.0.3 in a next release? I have also some other dependencies which require it, e.g., arktools

**Comment by khituras** [comment]
That's a tough one since the newest version of mallet still depends on trove 2.0.2. Mallet makes rather heavy use of trove afaik and it is obviously not compatible with 3.0.3. So at the moment I have no idea how to change this dependency except of upgrading mallet itself. For which I couldn't estimate how much work it is.

**Comment by khituras** [comment]
Update: There seems to exist a patch for Mallet using trove 3.0.3. Also, the Mallet developers seem to have the intention to abandon trove at all: https://github.com/mimno/Mallet/pull/17
Perhaps our Mallet version could be update using the patch and then, later, to abandon trove alltogether. However, I cannot give any time estimate or if it will be done at all since our group currently doesn't need it. Contributions are welcome, of course.

**Comment by khituras** [comment]
Update2: Looking at the trove 3.0.3 compatibility patch, its just imports that have to be adapted in terms of package names. however, it touches more than 80 files. If anyone has a good way to update the JCoRe mallet version like this, we should be able to include it in the next release, I guess.

**Comment by pkluegl** [comment]
Ok, thanks. Contributions are not ruled out, but time is always scarce. I already moved from mallet to factorie so I am not familiar with the mallet code anymore.

**Comment by khituras** [comment]
Fixed in branch 2.2.
